<label for="<?php echo $this->getFieldId('city')?>" class="required">
    <em>*</em>
    <?php echo $this->__('City') ?>
</label>
<div class="input-box">
    <input type="text"
        id="<?php echo $this->getFieldId('city')?>"
        name="<?php echo $this->getFieldName('city')?>"
        value="<?php echo $this->htmlEscape($this->getCity()) ?>"
        title="<?php echo $this->__('City') ?>"
        class="input-text required-entry" />
</div>