<label for="<?php echo $this->getFieldId('company')?>"<?php if ($this->isRequired()):?> class="required"<?php endif ?>>
    <?php if ($this->isRequired()):?><em>*</em><?php endif ?>
    <?php echo $this->__('Company') ?>
</label>
<div class="input-box">
    <input type="text"
        id="<?php echo $this->getFieldId('company')?>"
        name="<?php echo $this->getFieldName('company')?>"
        value="<?php echo $this->htmlEscape($this->getCompany()) ?>"
        title="<?php echo $this->__('Company') ?>"
        class="input-text<?php if ($this->isRequired()):?> required-entry<?php endif?>" />
</div>