<label for="<?php echo $this->getFieldId('fax')?>"<?php if ($this->isRequired()):?> class="required"<?php endif ?>>
    <?php if ($this->isRequired()):?><em>*</em><?php endif ?>
    <?php echo $this->__('Fax') ?>
</label>
<div class="input-box">
    <input type="text"
        id="<?php echo $this->getFieldId('fax')?>"
        name="<?php echo $this->getFieldName('fax')?>"
        value="<?php echo $this->htmlEscape($this->getFax()) ?>"
        title="<?php echo $this->__('Fax') ?>"
        class="input-text<?php if ($this->isRequired()):?> required-entry<?php endif?>" />
</div>