<label for="<?php echo $this->getFieldId('postcode')?>" class="required">
    <em>*</em>
    <?php echo $this->__('Zip/Postal Code') ?>
</label>
<div class="input-box">
    <input type="text"
        id="<?php echo $this->getFieldId('postcode')?>"
        name="<?php echo $this->getFieldName('postcode')?>"
        value="<?php echo $this->htmlEscape($this->getPostcode()) ?>"
        title="<?php echo $this->__('Zip/Postal Code') ?>"
        class="input-text required-entry" />
</div>