<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<div class="page-title">
    <h1><?php if($data->getAddressId()): ?><?php echo $this->__('Edit Address Entry') ?><?php else: ?><?php echo $this->__('New Address Entry') ?><?php endif ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $action ?>" method="post" id="form-validate">
    <div class="fieldset">
    <input type="hidden" name="address_id" value="<?php echo $data->getAddressId() ?>" />
    <input type="hidden" name="customer_id" id="address_id" value="<?php echo $data->getCustomerId() ?>" />
        <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($data)->toHtml() ?>
            </li>
            
    <?php $_company = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Company') ?>
        <?php if($_company->isEnabled()): ?>
            <li>
                <?php echo $_company->setCompany($this->getAddress()->getCompany())->toHtml() ?>
            </li>
        <?php endif ?>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Address') ?></h2>
        <ul class="form-list">
            <li class="wide">
                <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->htmlEscape($data->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                </div>
            </li>
        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
            <li class="wide">
                <div class="input-box">
                    <input type="text" name="street[]" value="<?php echo $this->htmlEscape($data->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address '.$_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                </div>
            </li>
        <?php endfor ?>
            <li class="fields">
                <div class="field">
                    <?php if ($this->getAddressPosition('city') == 1): ?>
                        <?php $_city = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_City') ?>
                        <?php echo $_city->setCity($this->getAddress()->getCity())->toHtml() ?>
                    <?php else: ?>
                        <?php $_postcode = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Postcode') ?>
                        <?php echo $_postcode->setPostcode($this->getAddress()->getPostcode())->toHtml() ?>
                    <?php endif ?>
                </div>
        <?php $_region = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Region') ?>
            <?php if ($_region->isEnabled()): ?>
                <div class="field">
                    <?php echo $_region->setRegion($this->getAddress()->getRegion())->toHtml() ?>
                </div>
            <?php else: ?>
                <div style="display:none;">
                    <input id="region"/>
                    <select id="region_id"/>
                </div>
            <?php endif ?>
            
            <?php if ($_region->isEnabled()): ?>
                </li>
                <li class="fields">
            <?php endif ?>
                <div class="field">
                    <?php if ($this->getAddressPosition('city') == 1): ?>
                        <?php $_postcode = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Postcode') ?>
                        <?php echo $_postcode->setPostcode($this->getAddress()->getPostcode())->toHtml() ?>
                    <?php else: ?>
                        <?php $_city = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_City') ?>
                        <?php echo $_city->setCity($this->getAddress()->getCity())->toHtml() ?>
                    <?php endif ?>
                </div>
            <?php if (!$_region->isEnabled()): ?>
                </li>
                <li class="fields">
            <?php endif ?>
                <div class="field">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <select name="country_id" id="country" title="<?php echo $this->__('Country') ?>" class="validate-select">
                            <?php echo $countries->toHtmlOptions($data->getCountryId()) ?>
                        </select>
                    </div>
                </div>
            </li>
    <?php $_telephone = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Telephone') ?>
    <?php $_fax = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Fax') ?>
        <?php if ($_telephone->isEnabled() || $_fax->isEnabled()): ?>
            <li class="fields">
            <?php if ($_telephone->isEnabled()): ?>
                <div class="field">
                    <?php echo $_telephone->setTelephone($this->getAddress()->getTelephone())->toHtml() ?>
                </div>
            <?php endif ?>
            <?php if ($_fax->isEnabled()): ?>
                <div class="field">
                    <?php echo $_fax->setFax($this->getAddress()->getFax())->toHtml() ?>
                </div>
            <?php endif ?>
            </li>
        <?php endif ?>
        <?php foreach ($primaryTypes as $code=>$type): ?>
            <li<?php if (!$address->isPrimary($type['address_type_id'])) echo ' class="control"' ?>>
            <?php if ($address->isPrimary($type['address_type_id'])): ?>
                <strong><?php echo $this->__("This is My Default %s Address", ucfirst($type['name'])) ?></strong>
            <?php else: ?>
                <input type="checkbox" id="primary_<?php echo $code ?>" name="primary_types[]" value="<?php echo $type['address_type_id'] ?>" class="checkbox" /><label for="primary_<?php echo $code ?>"><?php echo $this->__("Use as My Default %s Address", ucfirst($type['name'])) ?></label>
            <?php endif ?>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="<?php echo $this->getUrl('customer/address/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" class="button" title="<?php echo $this->__('Save Address') ?>"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //dataForm.setElementsRelation('country', 'state', '<?php echo $this->getUrl('directory/json/childRegion') ?>');
    new RegionUpdater('country', 'region', 'region_id', countryRegions, undefined, 'zip');
//]]>
</script>
