<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
                <?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
    <?php if($this->getShowAddressFields()): ?>
        <div class="fieldset">
            <input type="hidden" name="create_address" value="1" />
            <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
            <ul class="form-list">
        <?php $_company = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Company') ?>
        <?php $_telephone = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Telephone') ?>
            <?php if($_company->isEnabled() || $_telephone->isEnabled()): ?>
                <li class="fields">
                <?php if($_company->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_company->setCompany($this->getFormData()->getCompany())->toHtml() ?>
                    </div>
                <?php endif ?>
                <?php if ($_telephone->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_telephone->setTelephone($this->getFormData()->getTelephone())->toHtml() ?>
                    </div>
                <?php endif ?>
                </li>
            <?php endif ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                    </div>
                </li>
            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <li class="wide">
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address '.$_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields">
                    <div class="field">
                    <?php if ($this->getAddressPosition('city') == 1): ?>
                        <?php $_city = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_City') ?>
                        <?php echo $_city->setCity($this->getAddress()->getCity())->toHtml() ?>
                    <?php else: ?>
                        <?php $_postcode = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Postcode') ?>
                        <?php echo $_postcode->setPostcode($this->getAddress()->getPostcode())->toHtml() ?>
                    <?php endif ?>
                    </div>
            <?php $_region = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Region') ?>
                <?php if ($_region->isEnabled()): ?>
                    <div class="field">
                        <?php echo $_region->setRegion($this->getFormData()->getRegion())->toHtml() ?>
                    </div>
                <?php else: ?>
                    <div style="display:none;">
                        <input id="region"/>
                        <select id="region_id"/>
                    </div>
                <?php endif ?>
                
                <?php if ($_region->isEnabled()): ?>
                    </li>
                    <li class="fields">
                <?php endif ?>
                    <div class="field">
                    <?php if ($this->getAddressPosition('city') == 1): ?>
                        <?php $_postcode = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_Postcode') ?>
                        <?php echo $_postcode->setPostcode($this->getAddress()->getPostcode())->toHtml() ?>
                    <?php else: ?>
                        <?php $_city = $this->getLayout()->createBlock('Dull_Addressfields_Block_Widget_City') ?>
                        <?php echo $_city->setCity($this->getAddress()->getCity())->toHtml() ?>
                    <?php endif ?>
                    </div>
                <?php if (!$_region->isEnabled()): ?>
                    </li>
                    <li class="fields">
                <?php endif ?>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        </div>
    <?php endif; ?>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
